apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-worker-watch
spec:
  selector:
    matchLabels:
      app: kotsadm-worker-watch
  template:
    metadata:
      labels:
        app: kotsadm-worker-watch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kotsadm-worker-watch
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      serviceAccountName: kotsadm-worker-watch
      containers:
        - name: kotsadm-worker
          image: kotsadm-worker
          imagePullPolicy: IfNotPresent
          args: ["watch"]
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
          ports:
            - name: watch-server
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
          resources:
            limits:
              memory: 2048Mi
            requests:
              memory: 1024Mi
