apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-cluster-worker-image
spec:
  selector:
    matchLabels:
      app: ship-cluster-worker-image
  template:
    metadata:
      labels:
        app: ship-cluster-worker-image
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ship-cluster-worker-image
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      containers:
        - name: ship-cluster-worker
          image: ship-cluster-worker
          imagePullPolicy: IfNotPresent
          args: ["image"]
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
