apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-worker-analyze
spec:
  selector:
    matchLabels:
      app: kotsadm-worker-analyze
  template:
    metadata:
      labels:
        app: kotsadm-worker-analyze
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kotsadm-worker-analyze
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      serviceAccountName: kotsadm-worker-analyze
      containers:
        - name: kotsadm-worker
          image: kotsadm-worker
          imagePullPolicy: IfNotPresent
          args: ["analyze"]
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
          ports:
            - name: analyze-server
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
