steps:
  - commands:
      - make -C workerbuild-cache publish-cache
    branches: "master"

  - commands:
      - make -C worker build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          always-pull: true
          workdir: /go/src/github.com/replicatedhq/ship-cluster
    artifact_paths:
      - "worker/bin/**/*"

  - wait

  - commands:
      - mkdir -p worker/bin;
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - chmod +x worker/bin/ship-cluster-worker
      - make -C worker build-enterprise
    branches: "master"
    retry:
      automatic: true

  - wait

  - commands:
      - make -C worker publish-enterprise
    branches: "master"
    retry:
      automatic: true
