steps:
  - command: cd worker && make build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/ship-cluster-worker
    artifact_paths:
      - "bin/**/*"

  - wait

  - command: cd worker && make build-enterprise
    branches: master
    retry:
      automatic: true

  - wait

  - command: cd worker && make publish-enterprise
    branches: master
    retry:
      automatic: true
