steps:
  - commands:
      - make -C worker build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          workdir: /go/src/github.com/replicatedhq/kotsadm
    artifact_paths:
      - "worker/bin/**/*"

  - wait

  - commands:
      - mkdir -p worker/bin worker/deploy/bin
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - cp worker/bin/kotsadm-worker worker/deploy/bin/kotsadm-worker
      - chmod +x worker/deploy/bin/kotsadm-worker
      - make -C worker build_and_push
    branches: "master"
    retry:
      automatic: true

  - wait

  - commands:
      - make -C worker publish-enterprise
    branches: "master"
    retry:
      automatic: true

  - commands:
      - make -C worker publish-staging
    branches: "master"
    retry:
      automatic: true

  - block: "Release to production"
    branches: "master"

  - commands:
      - make -C worker publish-production
    branches: "master"
    retry:
      automatic: true
