steps:
  - commands:
      - cd worker
      - make build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/ship-cluster
    artifact_paths:
      - "worker/bin/**/*"

  - wait

  - commands:
      - mkdir -p worker/bin;
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - chmod +x worker/bin/ship-cluster-worker
      - cd worker
      - make build-enterprise
    branches: master
    retry:
      automatic: true

  - wait

  - commands:
      - cd worker
      - make publish-enterprise
    branches: master
    retry:
      automatic: true
