steps:
  - commands:
      - make -C worker build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          workdir: /go/src/github.com/replicatedhq/kotsadm
    artifact_paths:
      - "worker/bin/**/*"

  - wait

  # - commands:
  #     - make -C worker publish-enterprise
  #   branches: "master"
  #   retry:
  #     automatic: true

  - label: alpha
    commands:
      - mkdir -p worker/bin worker/deploy/bin
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - cp worker/bin/kotsadm-worker worker/deploy/bin/kotsadm-worker
      - chmod +x worker/deploy/bin/kotsadm-worker
      - make -C worker build-alpha publish-alpha
    branches: "master"

  - label: release
    commands:
      - if [ ! -z "$GIT_TAG" ]; then mkdir -p worker/bin worker/deploy/bin; fi
      - if [ ! -z "$GIT_TAG" ]; then buildkite-agent artifact download worker/bin/* . --step test-and-build; fi
      - if [ ! -z "$GIT_TAG" ]; then cp worker/bin/kotsadm-worker worker/deploy/bin/kotsadm-worker; fi
      - if [ ! -z "$GIT_TAG" ]; then chmod +x worker/deploy/bin/kotsadm-worker; fi
      - if [ ! -z "$GIT_TAG" ]; then make -C worker build-release publish-release; fi
