steps:
  - command: cd worker && make build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/ship-cluster/worker
    artifact_paths:
      - "worker/bin/**/*"

  - wait

  - command: cd worker && make build-enterprise
    branches: master
    retry:
      automatic: true

  - wait

  - commands:
      - cd worker && make publish-enterprise
      - cd worker && mkdir -p bin; buildkite-agent artifact download worker/bin/* bin --step test-and-build; chmod +x bin/ship-cluster-worker
    branches: master
    retry:
      automatic: true
