apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  name: helm-chart
spec:
  database: kotsadm-postgres
  name: helm_chart
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: helm_name
        type: text
        constraints:
          notNull: true
      - name: namespace
        type: text
        constraints:
          notNull: true
      - name: version
        type: int
      - name: first_deployed_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: last_deployed_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: is_deleted
        type: boolean
      - name: chart_version
        type: text
        constraints:
          notNull: true
      - name: app_version
        type: text
        constraints:
          notNull: true
