apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  name: helm-chart-source
spec:
  database: kotsadm-postgres
  name: helm_chart_source
  requires: []
  schema:
    postgres:
      primaryKey:
      - helm_chart_id
      - source
      columns:
      - name: helm_chart_id
        type: text
        constraints:
          notNull: true
      - name: source
        type: text
        constraints:
          notNull: true

