apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: image-watch-batch
spec:
  database: kotsadm-postgres
  name: image_watch_batch
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: user_id
        type: text
      - name: images_input
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
