apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: pullrequest-history
spec:
  database: kotsadm-postgres
  name: pullrequest_history
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: notification_id
        type: text
        constraints:
          notNull: true
      - name: pullrequest_number
        type: integer
        constraints:
          notNull: true
      - name: version_label
        type: text
        constraints:
          notNull: true
      - name: org
        type: text
        constraints:
          notNull: true
      - name: repo
        type: text
        constraints:
          notNull: true
      - name: branch
        type: text
      - name: root_path
        type: text
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: github_status
        type: text
        constraints:
          notNull: true
        default: 'unknown'
      - name: sequence
        type: integer
        default: "0"
      - name: source_branch
        type: text
        default: ''
