apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: watch-downstream-token
spec:
  database: kotsadm-postgres
  name: watch_downstream_token
  requires: []
  schema:
    postgres:
      primaryKey:
      - token
      columns:
      - name: token
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
