apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: watch-toubleshoot-collector
spec:
  database: kotsadm-postgres
  name: watch_troubleshoot_collector
  requires: []
  schema:
    postgres:
      primaryKey:
      - watch_id
      columns:
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: release_collector
        type: text
      - name: release_collector_updated_at
        type: timestamp without time zone
      - name: updated_collector
        type: text
      - name: updated_collector_updated_at
        type: timestamp without time zone
      - name: use_updated_collector
        type: boolean
