apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-worker-watch
spec:
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
        - name: kotsadm-worker
          image: kotsadm/kotsadm-worker
          imagePullPolicy: Always
          env:
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: GIT_SHA
              value: "GIT_SHA_PLACEHOLDER"
            - name: AWS_REGION
              value: us-east-1
            - name: GITHUB_INTEGRATION_ID
              value: "17891"
            - name: SHIP_IMAGE
              value: "replicated/ship"
            - name: SHIP_TAG
              value: "0.50.0"
            - name: SHIP_PULL_POLICY
              value: "Always"
