apiVersion: batch/v1
kind: Job
metadata:
  name: ship-cluster-migrations
spec:
  template:
    spec:
      containers:
      - name: migrations
        env:
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: ship-postgres
              key: uri

