apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kotsadm-api-bugsnag-secret
  namespace: default
spec:
  encryptedData:
    key: AgBBEmi//2O1Em/VXu/4FT9cydsOaWzpnxaYSkLnHdUbmLzsUor/FkLy+WG1b37qic6blYTvkvmflpD29fjve3INvL1au8OBE6C84gk2FlLF9XwKXEPbveB64DOFpW1aPnDCO1wm0mbKUCqDNNROvIihq33AFa8oOw83WwqkOHnmZ3vMNTKWWq6vs23+hJMZ4zIBRc7vU623QaT2O5sl+z6mqvtS4Hp77zq+2FhI1KqKUcm8ngMJaaexUe9BTu+l9bfZ+6qLPQfzRFzBZHPiRalnMFvsivVqz6wO4TmjW1AU9YKXv6PfOs6kLDVntoPzFZLnUljHaIs/E/ZL+ym7L8giqKG3tP2lQJQq6w2Emq/JZFdwga8Bhf0fNJhCjbCsQ4ezOYJ0rmMbwP53S7Ml9bLbfJJQDT615AL9EBiPMmVMkS9YnJQUD/r4+z5pIpb9euuKTHfS4JmalFIRbJKUQTmz20yFy0QdPI6m3PZjL83k4RbuwRm7RoZ0/vN1i9mgXwCubPOEj1oSjiFkB7GroV06bRbTBKHDPq1f/YUNYa3AXec8GbaEzXoCiCwBNtziX3xGWQCzDQO9WC98d7OSq9UX+XnvTlu+Puc8/+/dj6+k9CFraLnkd4azu3iGqMN3JAHP9ex6gGD/Ds8pL3wq2+Oz3CFPt54Nssze4fx7lDws1LE/w5juRvZXeovOjobQcorlNvgEh9GaMf4OpWDC8x7eWVlNbtaKXyigyyIyXVZPwg==

