apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
spec:
  template:
    metadata:
      labels:
        kots.io/backup-type: admin-console
      annotations:
        backup.velero.io/backup-volumes: backup
        kots.io/backup-type: admin-console
        pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "PGPASSWORD=password pg_dump -U shipcloud -h postgres > /backup/kotsadm-postgres.sql"]'
        pre.hook.backup.velero.io/timeout: 3m
    spec:
      containers:
        - name: kotsadm
          volumeMounts:
            - mountPath: /backup
              name: backup  
          env:
            - name: DISABLE_SPA_SERVING
              value: "1"
            - name: KOTSADM_TARGET_NAMESPACE
              value: "test"
              valueFrom: ~
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SHARED_PASSWORD_BCRYPT
              value: $2a$10$xZRsZCYgRDG90N1QEjBxGOBDrDGE.rpcMENV4qNNo7pozYTEPGMwS
            - name: SESSION_KEY
              value: this-is-not-too-secret
            - name: API_ENCRYPTION_KEY
              value: IvWItkB8+ezMisPjSMBknT1PdKjBx7Xc/txZqOP8Y2Oe7+Jy
            - name: REPLICATED_API_ENDPOINT
              value: http://replicated-app:3000
            - name: API_ENDPOINT
              value: http://kotsadm.default.svc.cluster.local:3000
            - name: API_ADVERTISE_ENDPOINT
              value: http://127.0.0.1:30065
            # - name: DISABLE_OUTBOUND_CONNECTIONS  
            #   value: "true"
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: backup
        