apiVersion: v1
kind: Service
metadata:
  name: kotsadm-api-lb
  labels:
    app: kotsadm
spec:
  type: NodePort
  ports:
  - name: http
    port: 8065
    targetPort: http
    nodePort: 30065
  selector:
    app: kotsadm
