steps:
  - commands:
      - cd ship-operator
      - make build-skaffold-cache

  - command: make ci
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/ship-operator
    artifact_paths:
      - "bin/**/*"

  - wait

  - command: "make build-enterprise"
    branches: master
    retry:
      automatic: true

  - wait

  - command: "make publish-enterprise"
    branches: master
    retry:
      automatic: true
