apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: airgap-install-status
spec:
  database: kotsadm-postgres
  name: airgap_install_status
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: integer
        constraints:
          notNull: true
      - name: updated_at
        type: timestamp without time zone
      - name: current_message
        type: text
