apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  name: app
spec:
  database: kotsadm-postgres
  name: app
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
      - name: icon_uri
        type: text
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: updated_at
        type: timestamp without time zone
      - name: slug
        type: text
        constraints:
          notNull: true
      - name: current_sequence
        type: integer
      - name: metadata
        type: text
      - name: last_update_check_at
        type: timestamp without time zone
