apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  name: app-version
spec:
  database: kotsadm-postgres
  name: app_version
  requires: []
  schema:
    postgres:
      primaryKey:
        - app_id
        - sequence
      columns:
      - name: app_id
        type: text
      - name: sequence
        type: integer
      - name: created_at
        type: timestamp without time zone
      - name: version_label
        type: text
        constraints:
          notNull: true

