apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: email-notification
spec:
  database: ship-cluster-postgres
  name: email_notification
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: notification_id
        type: text
        constraints:
          notNull: true
      - name: recipient
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
