apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: github-nonce
spec:
  database: ship-cluster-postgres
  name: github_nonce
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: nonce
        type: text
        constraints:
          notNull: true
      - name: expire_at
        type: timestamp without time zone
        constraints:
          notNull: true
