apiVersion: schemas.schemahero.io/v1alpha1
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: pending-pullrequest-notification
spec:
  database: ship-cluster-postgres
  name: pending_pullrequest_notification
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: pullrequest_history_id
        type: text
        constraints:
          notNull: true
      - name: org
        type: text
        constraints:
          notNull: true
      - name: repo
        type: text
        constraints:
          notNull: true
      - name: branch
        type: text
        constraints:
          notNull: true
      - name: root_path
        type: text
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: github_installation_id
        type: integer
        constraints:
          notNull: true
      - name: pullrequest_number
        type: integer
        default: '''-1''::integer'
      - name: watch_id
        type: text
