apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-output-files
spec:
  database: ship-cluster-postgres
  name: ship_output_files
  requires: []
  schema:
    postgres:
      primaryKey:
      - watch_id
      - sequence
      columns:
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: sequence
        type: integer
        constraints:
          notNull: true
        default: "0"
      - name: filepath
        type: text
        constraints:
          notNull: true
