apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-edit
spec:
  database: ship-cluster-postgres
  name: ship_edit
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: result
        type: text
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: finished_at
        type: timestamp without time zone
