apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-init-pending-user
spec:
  database: kotsadm-postgres
  name: ship_init_pending_user
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: ship_init_pending_id
        type: text
        constraints:
          notNull: true
