apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: supportbundle-upload-token
spec:
  database: ship-cluster-postgres
  name: supportbundle_upload_token
  requires: []
  schema:
    postgres:
      primaryKey:
      - token
      columns:
      - name: token
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
