apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: supportbundle
spec:
  database: ship-cluster-postgres
  name: supportbundle
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: slug # TODO: unique????
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: name
        type: text
      - name: size
        type: integer
      - name: status
        type: text
        constraints:
          notNull: true
      - name: tree_index
        type: text
      - name: analysis_id
        type: text
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: uploaded_at
        type: timestamp without time zone
      - name: is_archived
        type: boolean
