apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: watch-toubleshoot-analyzer
spec:
  database: ship-cluster-postgres
  name: watch_troubleshoot_analyzer
  requires: []
  schema:
    postgres:
      primaryKey:
      - watch_id
      columns:
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: release_analyzer
        type: text
      - name: release_analyzer_updated_at
        type: timestamp without time zone
      - name: updated_analyzer
        type: text
      - name: updated_analyzer_updated_at
        type: timestamp without time zone
      - name: use_updated_analyzer
        type: boolean
