apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: watch-cluster
spec:
  database: ship-cluster-postgres
  name: watch_cluster
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: github_path
        type: text
