version: 2

experimental:
  notify:
    branches:
      only:
        - master

defaults: &defaults
  docker:
  - image: replicated/gitops-builder:node8-go11
  working_directory: /go/src/github.com/replicatedhq/ship-operator-tools
  environment: &environment
    DOCKERFILE: Dockerfile.skaffold

jobs:
  is_upstream_master:
    <<: *defaults
    steps:
    - run: |
        set -veuo pipefail
        if [ "${CIRCLE_PROJECT_USERNAME}" != "replicatedhq" ]; then
          echo "refusing to build fork \"${CIRCLE_PROJECT_USERNAME}\""
          exit 1
        fi
        if [ "${CIRCLE_BRANCH}" != "master" ]; then
          echo "refusing to build branch \"${CIRCLE_BRANCH}\""
          exit 1
        fi

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: build
          command: make bin/ship-operator-tools test
      - persist_to_workspace:
          root: /go/src/github.com/replicatedhq/ship-operator-tools
          paths:
            - bin
            - pkg
            - cmd
            - scripts
            - vendor
            - Dockerfile.skaffold
            - Makefile

  build_docker_image:
    <<: *defaults
    steps:
    - setup_remote_docker:
        version: 17.06.0-ce
    - attach_workspace:
        at: /go/src/github.com/replicatedhq/ship-operator-tools
    - run: |
        export WORKDIR=/go/src/github.com/replicatedhq/ship-operator-tools
        docker build -f ${DOCKERFILE} \
          -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:7} \
          ${WORKDIR}
    - deploy:
        name: push image
        command: |
          docker tag \
            ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:7} \
            replicated/ship-operator-tools:${CIRCLE_SHA1:0:7}
          docker tag \
            ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:7} \
            replicated/ship-operator-tools
          docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
          docker push replicated/ship-operator-tools:${CIRCLE_SHA1:0:7}
          docker push replicated/ship-operator-tools

workflows:
  version: 2
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              ignore: /master/

  full_deploy:
    jobs:
      - is_upstream_master:
          filters:
            branches:
              only: master
      - build:
          requires:
          - is_upstream_master

      - build_docker_image:
          requires:
            - is_upstream_master
            - build
