apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  selector:
    matchLabels:
      app: kotsadm-web
  template:
    metadata:
      labels:
        app: kotsadm-web
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: kotsadm-web
          image: kotsadm-web
          imagePullPolicy: IfNotPresent
