apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 2
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - kotsadm-web
          topologyKey: "kubernetes.io/hostname"
  selector:
    matchLabels:
      app: kotsadm-web
  template:
    metadata:
      labels:
        app: kotsadm-web
    spec:
      containers:
        - name: kotsadm-web
          image: kotsadm-web
          imagePullPolicy: IfNotPresent
