steps:
  - command: make -C operator test build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          always-pull: true
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/kotsadm/operator
    artifact_paths:
      - "operator/bin/**/*"
      - "operator/pacts/**/*"

  - wait

  # TODO: doesn't look like these pacts exist
  # - commands:
  #     - mkdir -p operator/pacts
  #     - buildkite-agent artifact download operator/pacts/* operator/pacts --step test-and-build
  #     - make -C operator publish-pact
  #   branches: master
  #   retry:
  #     automatic: true

  # - wait

  - label: alpha
    commands:
      - mkdir -p operator/bin operator/deploy/bin
      - buildkite-agent artifact download operator/bin/* . --step test-and-build
      - cp operator/bin/kotsadm-operator operator/deploy/bin/kotsadm-operator
      - chmod +x operator/deploy/bin/kotsadm-operator
      - make -C operator build-alpha
    branches: "master"

  - label: release
    commands:
      - if [ ! -z "$GIT_TAG" ]; then mkdir -p operator/bin operator/deploy/bin; fi
      - if [ ! -z "$GIT_TAG" ]; then buildkite-agent artifact download operator/bin/* . --step test-and-build; fi
      - if [ ! -z "$GIT_TAG" ]; then cp operator/bin/kotsadm-operator operator/deploy/bin/kotsadm-operator; fi
      - if [ ! -z "$GIT_TAG" ]; then chmod +x operator/deploy/bin/kotsadm-operator; fi
      - if [ ! -z "$GIT_TAG" ]; then make -C worker build-release; fi

  # - wait

  # TODO: fixit
  # - command: "make build-enterprise"
  #   branches: master
  #   retry:
  #     automatic: true

  # - wait

  # TODO: fixit
  # - command: "make publish-enterprise"
  #   branches: master
  #   retry:
  #     automatic: true

