steps:
  - command: make ci
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          always-pull: true
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/kotsadm/operator
    artifact_paths:
      - "bin/**/*"
      - "pacts/**/*"
    branches: master

  - wait

  - command: "make publish-pact"
    branches: master
    retry:
      automatic: true

  - wait

  - command: "make publish"
    branches: master
    retry:
      automatic: true

  - wait

  - command: "make build-enterprise"
    branches: master
    retry:
      automatic: true

  - wait

  - command: "make publish-enterprise"
    branches: master
    retry:
      automatic: true

