steps:
  - command: make -C operator test build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          always-pull: true
          image: replicated/gitops-builder:buildkite
          workdir: /go/src/github.com/replicatedhq/kotsadm/operator
    artifact_paths:
      - "operator/bin/**/*"
      - "operator/pacts/**/*"
    branches: master

  - wait

  # TODO: doesn't look like these pacts exist
  # - commands:
  #     - mkdir -p operator/pacts
  #     - buildkite-agent artifact download operator/pacts/* operator/pacts --step test-and-build
  #     - make -C operator publish-pact
  #   branches: master
  #   retry:
  #     automatic: true

  # - wait

  - label: release
    commands:
      - mkdir -p operator/bin operator/deploy/bin
      - buildkite-agent artifact download operator/bin/* . --step test-and-build
      - cp operator/bin/kotsadm-operator operator/deploy/bin/kotsadm-operator
      - chmod +x operator/deploy/bin/kotsadm-operator
      - if [ -z "$GIT_TAG" ]; then make -C operator build-alpha publish-alpha; else git tag -f "$GIT_TAG" && make -C worker build-release publish-release; fi
    branches: "master"

  # - wait

  # TODO: fixit
  # - command: "make build-enterprise"
  #   branches: master
  #   retry:
  #     automatic: true

  # - wait

  # TODO: fixit
  # - command: "make publish-enterprise"
  #   branches: master
  #   retry:
  #     automatic: true

