apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-api
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: replicatedregistrykey
      containers:
        - name: kotsadm-api
          image: registry.replicated.com/ship-enterprise/kotsadm-api
          env:
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: session
                  key: key
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: ship-enterprise-postgres
                  key: uri
            - name: INIT_SERVER_URI
              value: "http://init-server:3000"
            - name: WATCH_SERVER_URI
              value: "http://watch-server:3000"
            - name: PINO_LOG_PRETTY
              value: "1"
            - name: S3_ENDPOINT
              value: http://minio.default.svc.cluster.local:9000/
            - name: S3_BUCKET_NAME
              value: ship-enterprise
            - name: AIRGAP_BUNDLE_S3_BUCKET
              value: airgap-ship-enterprise
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"
            - name: SHIP_API_ADVERTISE_ENDPOINT
              value: http://kotsadm-api.default.svc.cluster.local:3000
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-secret
            - name: GITHUB_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: integration-id
            - name: SHIP_API_ENDPOINT
              value: http://kotsadm-api.default.svc.cluster.local:3000
            - name: SHIP_API_ADVERTISE_ENDPOINT
              value: http://localhost:30065
            - name: GRAPHQL_PREM_ENDPOINT
              value: https://pg.replicated.com/graphql
          volumeMounts:
            - name: github-app-private-key
              mountPath: /keys/github
              readOnly: true
