apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-cluster-api
spec:
  selector:
    matchLabels:
      app: ship-cluster-api
  template:
    metadata:
      labels:
        app: ship-cluster-api
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ship-www
              topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ship-cluster-api
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      volumes:
        - name: github-app-private-key
          secret:
            secretName: github-app-private-key
      containers:
        - name: ship-cluster-api
          image: ship-cluster-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
            - name: debug
              containerPort: 9229
          env:
            - name: TRACER_NAME
              value: ship-cluster-api
            - name: GITHUB_PRIVATE_KEY_FILE
              value: /keys/github/private-key.pem
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-secret
            - name: GITHUB_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: integration-id
            - name: SHIP_API_ENDPOINT
              value: http://ship-cluster-api.default.svc.cluster.local:3000
            - name: SHIP_API_ADVERTISE_ENDPOINT
              value: http://docker.for.mac.localhost:30065
          volumeMounts:
            - name: github-app-private-key
              mountPath: /keys/github
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
