apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: shipwatches.ship.replicated.com
spec:
  group: ship.replicated.com
  names:
    kind: ShipWatch
    plural: shipwatches
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            actions:
              items:
                properties:
                  name:
                    type: string
                  pullRequest:
                    properties:
                      basePath:
                        type: string
                      github:
                        properties:
                          branch:
                            type: string
                          key:
                            properties:
                              valueFrom:
                                properties:
                                  secretKeyRef:
                                    properties:
                                      key:
                                        type: string
                                      name:
                                        type: string
                                      serviceAccountName:
                                        type: string
                                    required:
                                    - name
                                    - key
                                    - serviceAccountName
                                    type: object
                                type: object
                            type: object
                          owner:
                            type: string
                          path:
                            type: string
                          repo:
                            type: string
                          token:
                            properties:
                              valueFrom:
                                properties:
                                  secretKeyRef:
                                    properties:
                                      key:
                                        type: string
                                      name:
                                        type: string
                                      serviceAccountName:
                                        type: string
                                    required:
                                    - name
                                    - key
                                    - serviceAccountName
                                    type: object
                                type: object
                            type: object
                          username:
                            type: string
                        required:
                        - username
                        - owner
                        - repo
                        - branch
                        - token
                        - key
                        type: object
                      message:
                        type: string
                    required:
                    - message
                    - basePath
                    type: object
                  webhook:
                    properties:
                      payload:
                        type: string
                      secret:
                        type: string
                      uri:
                        type: string
                    required:
                    - uri
                    - payload
                    type: object
                required:
                - name
                type: object
              minItems: 1
              type: array
            environment:
              items:
                type: object
              type: array
            images:
              items:
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                  tag:
                    type: string
                required:
                - image
                - tag
                - imagePullPolicy
                type: object
              type: array
            state:
              properties:
                valueFrom:
                  properties:
                    secretKeyRef:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        serviceAccountName:
                          type: string
                      required:
                      - name
                      - key
                      - serviceAccountName
                      type: object
                  type: object
              type: object
            watchInterval:
              type: string
          required:
          - state
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
