steps:
  - commands:
      - cd migrations
      - make check-dups

  - wait

  - commands:
      - cd migrations
      - make build-skaffold-cache

  - commands:
      - cd migrations/fixtures
      - make deps build run
    label: "build-fixtures"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo
    artifact_paths:
      - "migrations/fixtures/fixtures.sql"

  - wait

  - commands:
      - buildkite-agent artifact download migrations/fixtures/fixtures.sql . --step build-fixtures
      - cd migrations/fixtures
      - make publish
    label: "publish-fixtures"

  - wait

  - commands:
      - cd migrations
      - make publish-enterprise
    branches: master
    retry:
      automatic: true

  - block: "Release to staging"
    branches: master

  - commands:
      - cd migrations
      - make publish-staging
    branches: master
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - block: "Release to production"
    branches: master

  - commands:
      - cd migrations
      - make publish-production
    branches: master
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"
