steps:
  - label: "schema-fixtures"
    artifact_paths:
      - "migrations/schema/fixtures.sql"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: schemahero/schemahero:alpha
          always-pull: true
          workdir: /repo
          shell: false
          volumes:
            - "/repo/migrations/fixtures/schema:/out"
            - "/repo/migrations/tables:/in"
          command: ["fixtures", "--input-dir", "/in", "--output-dir", "/out", "--dbname", "ship-cloud", "--driver", "postgres"]

  - wait

  - commands:
      - buildkite-agent artifact download migrations/schema/fixtures.sql . --step schema-fixtures
      - make -C migrations/fixtures deps build run
    label: "build-fixtures"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          always-pull: true
          workdir: /repo
    artifact_paths:
      - "migrations/fixtures/fixtures.sql"
    branches: "master"

  - wait

  - commands:
      - buildkite-agent artifact download migrations/fixtures/fixtures.sql . --step build-fixtures
      - cd migrations/fixtures
      - make publish
    label: "publish-fixtures"
    branches: "master"

  - wait

  - commands:
      - cd migrations
      - make publish-enterprise
    branches: master
    retry:
      automatic: true

  - block: "Release to staging"
    branches: "master"

  - commands:
      - cd migrations
      - make publish-staging
    branches: "master"
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - block: "Release to production"
    branches: "master"

  - commands:
      - cd migrations
      - make publish-production
    branches: "master"
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"
