steps:
  - command: make check-dups

  - wait

  - command: cd fixtures && make deps build run
    label: "build-fixtures"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo
    artifact_paths:
      - "fixtures/fixtures.sql"

  - wait

  - command: "cd fixtures && make publish"
    label: "publish-fixtures"

  - wait

  - command: make publish-enterprise
    branches: master

  - command: make publish-staging
    branches: master
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - block: "Release to production"
    branches: master

  - command: make publish-production
    branches: master
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"
