steps:
  - commands:
      - make -C migrations publish-enterprise
    branches: master
    retry:
      automatic: true

  - commands:
      - make -C migrations publish-staging
    branches: "master"
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - block: "Release to production"
    branches: "master"

  - commands:
      - make -C migrations publish-production
    branches: "master"
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"
