apiVersion: clusters.replicated.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample
spec:
  shipApiServer: http://localhost:8065
  token: 08814725d458b87fa06ad8f5647fe85e
