apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sqs
spec:
  template:
    metadata:
      labels:
        app: sqs
    spec:
      containers:
      - name: sqs
        image: vsouza/sqs-local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9324
          name: sqs





