apiVersion: databases.schemahero.io/v1alpha2
kind: Database
metadata:
  name: ship-cluster-postgres
connection:
  postgres:
    uri:
      valueFrom:
        secretKeyRef:
          name: ship-enterprise-postgres
          key: uri
