bases:
  - ../dev
  - ./minio
  - ../../../api/kustomize/overlays/dev
  - ../../../web/kustomize/overlays/dev
  - ../../../operator/kustomize/overlays/dev
  - ../../../migrations/kustomize/overlays/dev

patches:
  - ./deployment.yaml