apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-operator
spec:
  template:
    spec:
      containers:
        - name: kotsadm-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: KOTSADM_API_ENDPOINT
              value: http://kotsadm-api:3000
            - name: KOTSADM_TARGET_NAMESPACE
              value: "test"
              valueFrom: ~
