apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  template:
    spec:
      containers:
        - name: kotsadm-web
          image: kotsadm/kotsadm-web
          imagePullPolicy: Always
          env:
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: GIT_SHA
              value: "GIT_SHA_PLACEHOLDER"
            - name: AWS_REGION
              value: us-east-1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: http
              containerPort: 3000
