apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-worker-update
spec:
  template:
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: replicatedregistrykey
      containers:
        - name: kotsadm-worker
          image: registry.replicated.com/ship-enterprise/kotsadm-worker
          env:
            - name: SHIP_IMAGE
              value: "replicated/ship"
            - name: SHIP_TAG
              value: "0.50.0"
            - name: SHIP_PULL_POLICY
              value: "IfNotPresent"
            - name: LOG_LEVEL
              value: warn
            - name: S3_ENDPOINT
              value: http://minio.default.svc.cluster.local:9000/
            - name: S3_BUCKET_NAME
              value: ship-enterprise
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: ship-enterprise-postgres
                  key: uri
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-app-private-key
                  key: private-key.pem
            - name: GITHUB_INTEGRATION_ID
              value: ""
