apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-operator
spec:
  template:
    spec:
      nodeSelector:
        # TODO: what should selectors be?
        replicated/node-pool: privileged
      containers:
        - name: kotsadm-operator
          image: kotsadm/kotsadm-operator
          env:
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: AWS_REGION
              value: us-east-1
