apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-cluster-api
spec:
  template:
    spec:
      containers:
      - name: ship-cluster-api
        env:
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: session
              key: key
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: ship-postgres   # This secret is created in the ship-cluster-db project
              key: uri
        - name: INIT_SERVER_URI
          value: "http://init-server:3000"
        - name: WATCH_SERVER_URI
          value: "http://watch-server:3000"
        - name: PINO_LOG_PRETTY
          value: "1"
        - name: S3_BUCKET_NAME
          value: "shipbucket"
        - name: S3_ENDPOINT
          value: http://s3.default.svc.cluster.local:4569/
        - name: S3_ACCESS_KEY_ID
          value: abc
        - name: S3_SECRET_ACCESS_KEY
          value: "123"
        - name: S3_BUCKET_ENDPOINT
          value: "true"
