apiVersion: v1
kind: Service
metadata:
  name: ship-cluster-api-lb
  labels:
    app: ship-cluster-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8065
    targetPort: http
  selector:
    app: ship-cluster-api
