apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kotsadm-api-bugsnag-secret
  namespace: default
spec:
  encryptedData:
    key: AgA1EOsnJaFSsgqIx6sDXKMdWbKRDmMKJz7t2kCxuiK61Yt5bgMLTlBjqzmBg0aadbt+4qDHEq5QFjiOhXnPRj7Qh7ijzFe0tAw9VhRE0WZrEQCMIoFfsv0iqihgsNB54GibbbSrdyX9+w68NAYSqVNTLeLqp+eNV3qWMJIm7WLoXdbSOuJxt7wHoV4gmgQ2MR4eKkOjjABtjSiH2iF/L4rN+z1YeJw02GahmlAKWeFQJ9Q8oBk7BqnQ6OzSn0/PLTNy91eMHHQvECXv2Y+GrGeC4cwogsfWQetzKLtZJnwAgLFnHyAAZZwND1k3gnERRb4vJc8GmyM+dnHiIzbMPblR/kLwXjv3eSrAVqoOM8arbDvDDQKnK1dd01ZnEo/pqgSchLbnZkolPEGjizsfQR/F+bHiOb/Yczkzv/NomGuptuTkV5dWYNh4yN5BE2QaQQXZN5Wgk/B3cYtbL3qGcYxf4tbQdpnw2wBq/r9mPoaVo2R1cK14WdIe4UY2X6Curzh/YVSs11xXu/9CyrDYKTQDd3nqvyouTPj2RL/6ZD26KnqBKwpJnxYm+jDFibXZNiGYNMcUfmp7XxoEUor46kl9ievTdreOnWDDK1xhWlcSKMNNA0x8jJO1LopAyIaxlbQubcIBugXr6s95I5r7cZfOGPmn8xPRA/LIHrKeQw01xUp/A/QXDqBx2xHaG3/dIkds8WtKxn968gRcC9CEBCmoUyJfkUp092/SuDM9ljR+qA==

