apiVersion: ship.replicated.com/v1beta1
kind: ShipWatch
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-app
spec:
  actions:
  - name: webhook
    webhook:
      uri: http://60aca62c.ngrok.io
      payload: '{"example":"payload"}'
  state:
    valueFrom:
      secretKeyRef:
        name: sample-chart-state
        key: state.json
        serviceAccountName: default
