apiVersion: ship.replicated.com/v1beta1
kind: ShipWatch
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-app
spec:
  actions:
  - name: pr
    pullRequest:
      message: "Update to sample app"
      basePath: /sample-app
      github:
        username: marccampbell
        owner: marccampbell
        repo: ship-apps
        branch: master
        key:
          valueFrom:
            secretKeyRef:
              name: sample-chart-state
              key: key.pem
              serviceAccountName: default
        token:
          valueFrom:
            secretKeyRef:
              name: sample-chart-state
              key: github.token
              serviceAccountName: default
  state:
    valueFrom:
      secretKeyRef:
        name: sample-chart-state
        key: state.json
        serviceAccountName: default
  watchInterval: "15s"
