apiVersion: batch/v1
kind: Job
metadata:
  name: ship-cluster-local-cluster
spec:
  template:
    spec:
      serviceAccountName: kotsadm-api
      containers:
        - name: ship-cluster-local-cluster
          env:
            - name: ENSURE_LOCAL_CLUSTER
              value: '1'
