steps:
  - commands:
      - make -C web build-cache publish-cache

  - command: cd web && make deps test && yarn run publish:pact
    label: "test-and-build"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - PACT_BROKER_USERNAME
            - PACT_BROKER_PASSWORD

  - wait

  - trigger: "ship-cluster-api"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - command: cd web && make deps build-enterprise
    label: "build-enterprise"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
    artifact_paths:
      - "web/dist/**/*"

  - wait

  - commands:
      - mkdir -p web/dist
      - buildkite-agent artifact download web/dist/* . --step build-enterprise
      - make -C web publish-enterprise
    branches: "master"

  - block: "Release to staging"
    branches: "master"

  - commands:
      - mkdir -p web/dist
      - buildkite-agent artifact download web/dist/* . --step build-staging
      - make -C web publish-staging
    branches: "master"

  - block: "Release to production"
    branches: "master"

  - commands:
      - mkdir -p web/dist
      - buildkite-agent artifact download web/dist/* . --step build-production
      - make -C web publish-production
    branches: "master"
