steps:
  - command: cd web && make deps test && yarn run publish:pact
    label: "test-and-build"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - PACT_BROKER_USERNAME
            - PACT_BROKER_PASSWORD

  - wait

  - trigger: "ship-cluster-api"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - commands:
      - make -C web deps build-enterprise
    label: "build-enterprise"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
    artifact_paths:
      - "web/dist/**/*"

  - commands:
      - make -C web deps build-staging
    label: "build-staging"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
    artifact_paths:
      - "web/dist/**/*"

  - commands:
      - make -C web deps build-production
    label: "build-production"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
    artifact_paths:
      - "web/dist/**/*"

  - wait

  - label: publish-enterprise
    commands:
      - mkdir -p web/dist
      - buildkite-agent artifact download web/dist/* . --step build-enterprise
      - make -C web publish-enterprise
    branches: "master"

  - label: publish-staging
    commands:
      - mkdir -p web/dist
      - buildkite-agent artifact download web/dist/* . --step build-staging
      - make -C web publish-staging
    branches: "master"
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - block: "Release to production"
    branches: "master"

  - label: publish-production
    commands:
      - mkdir -p web/dist
      - buildkite-agent artifact download web/dist/* . --step build-production
      - make -C web publish-production
    branches: "master"
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"
