steps:
  - command: cd web && make deps test && yarn run publish:pact
    label: "test-and-build"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - PACT_BROKER_USERNAME
            - PACT_BROKER_PASSWORD

  - wait

  - trigger: "kotsadm-api"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        GIT_TAG: "${GIT_TAG}"

  - wait

  - commands:
      - make -C web deps build-kotsadm
    label: "build-kotsadm"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - BUILDKITE_COMMIT
    artifact_paths:
      - "web/dist/**/*"

  - commands:
      - make -C web deps build-replicated-staging
    label: "build-replicated-staging"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - BUILDKITE_COMMIT
    artifact_paths:
      - "web/dist/**/*"

  - commands:
      - make -C web deps build-replicated-production
    label: "build-replicated-production"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - BUILDKITE_COMMIT
    artifact_paths:
      - "web/dist/**/*"

  - wait

  - label: publish-kotsadm
    branches: "master"
    command: |
      # publish always, image tag is based on git tag
      mkdir -p web/dist;
      buildkite-agent artifact download web/dist/* . --step build-kotsadm

      if [ -z "$GIT_TAG" ]; then \
        make -C web publish-kotsadm-alpha;
      else \
        make -C web publish-kotsadm-tag;
      fi

  - label: publish-replicated-staging
    branches: "master"
    command: |
      mkdir -p web/dist;
      if [ -z "$GIT_TAG" ]; then \
        buildkite-agent artifact download web/dist/* . --step build-replicated-staging && \
        make -C web publish-replicated-staging release-replicated-staging;
      fi

  - label: publish-replicated-production
    branches: "master"
    command: |
      mkdir -p web/dist;
      if [ -z "$GIT_TAG" ]; then \
      else \
        git tag -f "$GIT_TAG" && \
        buildkite-agent artifact download web/dist/* . --step build-replicated-production && \
        make -C web publish-replicated-production release-replicated-production;
      fi
