steps:
  - command: cd web && make deps test && yarn run publish:pact
    label: "test-and-build"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - PACT_BROKER_USERNAME
            - PACT_BROKER_PASSWORD

  - wait

  - trigger: "kotsadm-api"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        GIT_TAG: "${GIT_TAG}"

  - wait

  # TODO: fixit
  # - commands:
  #     - make -C web deps build-enterprise
  #   label: "build-enterprise"
  #   branches: "master"
  #   plugins:
  #     - docker#v3.0.1:
  #         image: replicated/gitops-builder:buildkite
  #         workdir: /repo/web
  #         environment:
  #           - BUILDKITE_COMMIT
  #   artifact_paths:
  #     - "web/dist/**/*"

  - commands:
      - make -C web deps build-alpha
    label: "build-alpha"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - BUILDKITE_COMMIT
    artifact_paths:
      - "web/dist/**/*"

  - commands:
      - make -C web deps build-release
    label: "build-release"
    branches: "master"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          workdir: /repo/web
          environment:
            - BUILDKITE_COMMIT
    artifact_paths:
      - "web/dist/**/*"

  - wait

  # - label: publish-enterprise
  #   commands:
  #     - mkdir -p web/dist
  #     - buildkite-agent artifact download web/dist/* . --step build-enterprise
  #     - make -C web publish-enterprise
  #   branches: "master"

  - label: publish
    branches: "master"
    command: |
      mkdir -p web/dist;
      if [ -z "$GIT_TAG" ]; then \
        buildkite-agent artifact download web/dist/* . --step build-alpha && \
        make -C web publish-alpha;
      else \
        git tag -f "$GIT_TAG" && \
        buildkite-agent artifact download web/dist/* . --step build-release && \
        make -C web publish-release;
      fi
