apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ship-cluster-postgres
  namespace: default
spec:
  encryptedData:
    uri: AgCZvABvKJr9NCv9p2p91azX+hYpVf3Q7aljQoP+Ox00XFiYgGB/dmwQGs5/dOMVtCo5eaGf6YL2czoJ9RLE8g+mrWYcKJWv1nEOFVahVaPzWQ/PSf8oNJ25mBF9Lj5/AmvuvsASNXxLpk4VEWsgvWi1US9uk0zdlLnO6PGpOtPkk3/XnOImRhRkwgNBuObx0YXM+FKD74L7qEUH8qpFQGcXOtC+zN5XepDxE1Ka5Mt6eoxnfb//cZRGYUt7W3DzwIw1ie6+uEWqpPviB4FG7WEschO/ciztnv8ocIJTAQpRa9+4qVUDvC3M3w9CPqVTFWeG5gX60+XUqM7z4m18y8pBPUK2KeHkjlByungujs6T1LvF5leybXfvYoPPOffR6r9cO3XPiMh/uIDtXj850blZ6NQ4EuSThUxNku1cjtKK91+wwBXUU48fPlG3pZfXBv1bIRqp+E0KFH8cQKk45qk7r5pfk7Hw0n976Dr6l5DmQxQ4iMoz4fmgL0RquJSgpFmAvnOCJ8uPblgZT2IRzYSVAN7gEqCMMZr6KQWlhLgfJTvCHcz4P4nhOfxlSAGuTBPW6FvYojO68y3xpFCLmkzUXZ+dwcN56ihKOzRV3KhnG07FhBxD9HSh9cozOXNqeJ0UIHKBJTqEqlEyR10+s6fX8tuxVMDICBJunKxGoAwadw77RQFl24jmxKCzMHnHfhKvZH6iM6yGyUdpt6AI7HfpW9++RiCZNmkFQ5WU80EF4KvLuXKW29CaRuutEatlRnjpVWsrGQv6g/5uxYFRWOYeIYyoUa3qZeFJSCyTJi/flygRkJY7u8XJjfiQ0f+H1RxFFVQ4CahdxAK3UptNLEQr9U71MyrNUOkTNYEvQOIuxKLmRFTHkCkEq+CUbHyx1aY7tC0bSJejXOChJfi0EPaF7WP98Lrd

