apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-operator
spec:
  template:
    spec:
      containers:
        - name: kotsadm-operator
          env:
            - name: DEFAULT_NAMESPACE
              value: "test"
