steps:
  - commands:
      - make -C api build-cache publish-cache

  - commands:
      - docker-compose -f api/test/docker-compose.yml down
      - docker-compose -f api/test/docker-compose.yml pull
      - docker-compose -f api/test/docker-compose.yml build
      - docker-compose -f api/test/docker-compose.yml up --exit-code-from ship-cluster-api
      - docker-compose -f api/test/docker-compose.yml down

  - commands:
      - make -C api deps build pkg
    label: "build"
    plugins:
      - docker#v3.0.1:
          always-pull: true
          image: replicated/gitops-builder:buildkite
          workdir: /repo/api
    artifact_paths:
      - "api/build/**/*"
      - "api/bin/**/*"

  - wait

  - commands:
     - make -C api can-i-deploy

  - wait

  - commands:
      - mkdir -p api/build
      - buildkite-agent artifact download api/build/* . --step build
      - mkdir -p api/bin
      - buildkite-agent artifact download api/bin/* . --step build
      - chmod +x api/bin/ship-cluster-api
      - chmod +x api/bin/shipcloudctl
      - cd api
      - make build-enterprise
    branches: "master"

  - wait

  - commands:
      - make -C api publish-enterprise
    branches: "master"

  - commands:
      - make -C api publish-staging
    branches: "master"

  - block: "Release to production"
    branches: "master"

  - commands:
      - make -C api publish-production
    branches: "master"

