steps:
  - commands:
      - docker-compose -f api/test/docker-compose.yml down
      - docker-compose -f api/test/docker-compose.yml pull
      - docker-compose -f api/test/docker-compose.yml build
      - docker-compose -f api/test/docker-compose.yml up --exit-code-from kotsadm-api
      - docker-compose -f api/test/docker-compose.yml down

  - commands:
      - make -C api deps build
    label: "build"
    plugins:
      - docker#v3.0.1:
          always-pull: true
          image: replicated/gitops-builder:buildkite
          workdir: /repo/api
    artifact_paths:
      - "api/build/**/*"
      - "api/bin/**/*"

  - wait

  - commands:
     - make -C api can-i-deploy

  - wait

  - label: release
    commands:
      - if [ -z "$GIT_TAG" ]; then make -C api build-alpha publish-alpha; else make -C api build-release publish-release; fi
    branches: "master"
