bases:
  - ../../base
  - ../../../web/kustomize/overlays/kotsadm
  - ../../../api/kustomize/overlays/kotsadm
  - ../../../worker/kustomize/overlays/kotsadm
  - ../../../migrations/kustomize/overlays/kotsadm
