apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: kotsadm-web
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-id
            - name: GITHUB_INSTALL_URL
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: install-url
            - name: SHIP_CLUSTER_API_SERVER
              value: "http://localhost:30065"
            - name: SHIP_CLUSTER_WEB_URI
              value: "http://localhost:8000"
